"""Added phone, age, location, land_size, and crop fields to User model

Revision ID: 363503fcd931
Revises: 21e9ce8b7eb0
Create Date: 2025-03-25 21:13:40.335676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363503fcd931'
down_revision = '21e9ce8b7eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('land_size', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('crop', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('crop')
        batch_op.drop_column('land_size')
        batch_op.drop_column('location')
        batch_op.drop_column('age')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
